apps/snippet/urls.py
from django.conf.urls.defaults import patterns, url
from django.conf import settings


urlpatterns = patterns('apps.snippet.views',
    url('^$',
        'snippet_new', name='snippet_new'),

    url(r'^explore$',
        'explore', name='snippet_explore'),
                       
    url(r'^guess/$',
        'guess_lexer', name='snippet_guess_lexer'),
                       
    url(r'^diff/$',
        'snippet_diff', name='snippet_diff'),

    url(r'^your-latest/$',
        'snippet_userlist', name='snippet_userlist'),
                       
    url(r'^your-settings/$',
        'userprefs', name='snippet_userprefs'),
                       
    url(r'^(?P<snippet_id>[a-zA-Z0-9]{4})/$',
        'snippet_details', name='snippet_details'),
                       
    url(r'^(?P<snippet_id>[a-zA-Z0-9]{4})/delete/$',
        'snippet_delete', name='snippet_delete'),

    url(r'^(?P<snippet_id>[a-zA-Z0-9]{4})/raw/$',
        'snippet_details',
          {'template_name': 'snippet/snippet_details_raw.djhtml',
           'is_raw': True},
        name='snippet_details_raw'),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',
        'django.views.generic.simple.direct_to_template',
        {'template': 'index.djhtml'},
        name='home'),
    url(r'^about$',
        'django.views.generic.simple.direct_to_template',
        {'template': 'about.djhtml'},
        name='about'),
    url(r'^help$',
        'django.views.generic.simple.direct_to_template',
        {'template': 'help.djhtml'},
        name='help'),
    url(r'^discuss$',
        'django.views.generic.simple.direct_to_template',
        {'template': 'discuss.djhtml'},
        name='discuss'),
    url(r'^code$',
        'views.code',
        name='code'),
    url(r'^login',
        'views.login_register',
        name='login'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout',
        {'template_name' : 'index.djhtml', 'next_page' : '/'}
    ),
    url(r'^accounts/', include('registration.urls')),
    url(r'^licenses/', include('agora.apps.free_license.urls')),
    url(r'^users/', include('agora.apps.profile.urls')),
    url(r'^snippet/', include('agora.apps.snippet.urls')),
    url(r'^bundles/', include('agora.apps.bundle.urls')),
)

#Let Django itself serve static data during debugging
from django.conf import settings

if settings.DEBUG:
     urlpatterns += patterns('',
                    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                    {'document_root': 'static/', 'show_indexes': True}),
                    )

apps/snippet/models.py
import datetime
import difflib
import random

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey

from apps.snippet.highlight import LEXER_DEFAULT, LEXER_LIST, pygmentize


t = 'abcdefghijkmnopqrstuvwwxyzABCDEFGHIJKLOMNOPQRSTUVWXYZ1234567890'
def generate_secret_id(length=4):
    return ''.join([random.choice(t) for i in range(length)])

class SnippetManager(models.Manager):
    def public(self):
        """
        Returns all the snippets that were created by registered users
        and thus can be publicly listed.
        """
        return self.filter(author__isnull=False)


class Snippet(MPTTModel):
    objects = SnippetManager()
    secret_id = models.CharField(_(u'Secret ID'), max_length=4, blank=True)
    title = models.CharField(_(u'Title'), max_length=120, blank=True)
    author = models.ForeignKey(User, max_length=30, blank=True, null=True)
    content = models.TextField(_(u'Content'), )
    content_highlighted = models.TextField(_(u'Highlighted Content'),
                                           blank=True)
    lexer = models.CharField(_(u'Lexer'),
                             max_length=30,
                             choices=LEXER_LIST,
                             default=LEXER_DEFAULT)
    published = models.DateTimeField(_(u'Published'), blank=True)
    expires = models.DateTimeField(_(u'Expires'), blank=True, help_text='asdf')
    parent = TreeForeignKey('self', null=True, blank=True,
                               related_name='children')
    num_views = models.IntegerField(default=0)

    class Meta:
        ordering = ('-published',)

    def get_linecount(self):
        return len(self.content.splitlines())

    def content_splitted(self):
        return self.content_highlighted.splitlines()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.published = datetime.datetime.now()
            self.secret_id = generate_secret_id()
        self.content_highlighted = pygmentize(self.content, self.lexer)
        super(Snippet, self).save(*args, **kwargs)

    def get_title(self):
        return self.title or _('Snippet #%d' % self.id)

    @models.permalink
    def get_absolute_url(self):
        return ('snippet_details', (self.secret_id,))

    def __unicode__(self):
        return '%s' % self.secret_id


class CodeLanguage(models.Model):
    name = models.CharField(max_length=64)

    def __unicode__(self):
        return name

apps/snippet/forms.py
import datetime

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from apps.snippet.models import Snippet
from apps.snippet.highlight import LEXER_LIST_ALL, LEXER_LIST, LEXER_DEFAULT

#===============================================================================
# Snippet Form and Handling
#===============================================================================

EXPIRE_CHOICES = (
    (3600, _(u'In one hour')),
    (3600*24*7, _(u'In one week')),
    (3600*24*30, _(u'In one month')),
    (3600*24*30*12*100, _(u'Save forever')), # 100 years, I call it forever ;)
)

EXPIRE_DEFAULT = 3600*24*30

class SnippetForm(forms.ModelForm):
    file = forms.FileField(help_text=_("If the snippet you want to post is \
        saved as a file on your computer, you can upload it directly rather \
        than having to copy and paste it into the box above. If a file \
        is specified, the text in the content field above will be \
        ignored."),
        required=False)

    expire_options = forms.ChoiceField(
        choices=EXPIRE_CHOICES,
        initial=EXPIRE_DEFAULT,
        label=_(u'Expires'),
    )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super(SnippetForm, self).__init__(*args, **kwargs)
        self.request = request

        try:
            if self.request.session['userprefs'].get('display_all_lexer',
                                                     False):
                self.fields['lexer'].choices = LEXER_LIST_ALL
        except KeyError:
            pass

        try:
            self.fields['author'].initial = \
                    self.request.session['userprefs'].get('default_name', '')
        except KeyError:
            pass

        # Make the content field not required (validated in clean())
        self.fields['content'].required = False
        self.fields['title'].required = True

    def clean(self):
        cleaned_data = super(SnippetForm, self).clean()
        file_data = cleaned_data.get('file')
        content = cleaned_data.get('content')

        if file_data:
            file_data.open()
            content_type = file_data.content_type

            # Do some very basic checking of types. NOT SECURE.
            if (content_type.startswith('text/') or
                content_type.startswith('application')):
                cleaned_data['content'] = file_data.read()
            else:
                raise forms.ValidationError(_("Please ensure that you upload \
                    a text file."))
        elif not content:
            # No snippet data specified
            raise forms.ValidationError(_("Please specify some content for \
                the snippet, either in the content field or by uploading \
                a file."))

        return cleaned_data

    def save(self, parent=None, *args, **kwargs):

        # Set parent snippet
        if parent:
            self.instance.parent = parent

        # Add expire datestamp
        self.instance.expires = datetime.datetime.now() + \
            datetime.timedelta(seconds=int(self.cleaned_data['expire_options']))

        # Save snippet in the db
        super(SnippetForm, self).save(*args, **kwargs)

        # Add the snippet to the user session list
        if self.request.session.get('snippet_list', False):
            if len(self.request.session['snippet_list']) >= \
                   getattr(settings, 'MAX_SNIPPETS_PER_USER', 10):
                self.request.session['snippet_list'].pop(0)
            self.request.session['snippet_list'] += [self.instance.pk]
        else:
            self.request.session['snippet_list'] = [self.instance.pk]

        return self.request, self.instance

    class Meta:
        model = Snippet
        fields = (
            'title',
            'content',
            'lexer',
        )


#===============================================================================
# User Settings
#===============================================================================

USERPREFS_FONT_CHOICES = [(None, _(u'Default'))] + [
    (i, i) for i in sorted((
        'Monaco',
        'Bitstream Vera Sans Mono',
        'Courier New',
        'Consolas',
    ))
]

USERPREFS_SIZES = [(None, _(u'Default'))] + [(i, '%dpx' % i) for i in range(5, 25)]

class UserSettingsForm(forms.Form):

    default_name = forms.CharField(label=_(u'Default Name'), required=False)
    display_all_lexer = forms.BooleanField(
        label=_(u'Display all lexer'),
        required=False,
        widget=forms.CheckboxInput,
        help_text=_(u'This also enables the super secret ' \
                     '\'guess lexer\' function.'),
    )
    font_family = forms.ChoiceField(label=_(u'Font Family'),
                                    required=False,
                                    choices=USERPREFS_FONT_CHOICES)
    font_size = forms.ChoiceField(label=_(u'Font Size'),
                                  required=False,
                                  choices=USERPREFS_SIZES)
    line_height = forms.ChoiceField(label=_(u'Line Height'),
                                    required=False,
                                    choices=USERPREFS_SIZES)

apps/snippet/views.py
import difflib

from django.shortcuts import render_to_response, \
     get_object_or_404, get_list_or_404, render, redirect
from django.template.context \
     import RequestContext
from django.http \
     import HttpResponseRedirect, HttpResponseBadRequest, \
     HttpResponse, HttpResponseForbidden
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils import simplejson

from apps.snippet.forms import SnippetForm, UserSettingsForm
from apps.snippet.models import Snippet
from apps.snippet.highlight import pygmentize, guess_code_lexer, \
     LEXER_LIST
from apps.pygments_style.models import PygmentsStyle


def explore(request):
    context = {
        'recent_snippets': Snippet.objects.public()[:20]
    }

    return render(request, 'snippet/explore.html', context)


def snippet_new(request):
    if request.method == "POST":
        snippet = Snippet()

        if request.user.is_authenticated():
            snippet.author = request.user

        snippet_form = SnippetForm(request.POST,
                                   request.FILES,
                                   request=request,
                                   instance=snippet)

        if snippet_form.is_valid():
            request, new_snippet = snippet_form.save()
            return redirect(new_snippet)
    else:
        snippet_form = SnippetForm(request=request)

    recent = Snippet.objects.public()[:10]

    context = {
        'snippet_form': snippet_form,
        'recent_snippets' : recent,
    }

    return render(request, 'snippet/snippet_new.djhtml', context)


def snippet_details(request, snippet_id,
    template_name='snippet/snippet_details.djhtml', is_raw=False):
    snippet = get_object_or_404(Snippet, secret_id=snippet_id)
    snippet.num_views += 1
    snippet.save()

    tree = snippet.get_root()
    tree = tree.get_descendants(include_self=True)

    if snippet.title.startswith('Re: '):
        reply_title = snippet.title
    else:
        reply_title = 'Re: %s' % snippet.title

    new_snippet_initial = {
        'content': snippet.content,
        'lexer': snippet.lexer,
        'title': reply_title,
    }

    if request.method == "POST":
        snippet_form = SnippetForm(request.POST,
                                   request.FILES,
                                   request=request,
                                   initial=new_snippet_initial)
        if snippet_form.is_valid():
            request, new_snippet = snippet_form.save(parent=snippet)
            return redirect(new_snippet)
    else:
        snippet_form = SnippetForm(initial=new_snippet_initial,
                                   request=request)

    if request.user.is_authenticated():
        default_pygments_style = request.user.get_profile().pygments_style
    else:
        default_pygments_style = PygmentsStyle.objects.get(pk=1)

    context = {
        'snippet_form': snippet_form,
        'snippet': snippet,
        'lines': range(snippet.get_linecount()),
        'tree': tree,
        'language': dict(LEXER_LIST)[snippet.lexer],
        'pygments_styles': PygmentsStyle.objects.all(),
        'default_style': default_pygments_style,
        'no_descendants': len(tree) == 1,
    }

    response = render(request, template_name, context)

    if is_raw:
        response['Content-Type'] = 'text/plain'
        return response
    else:
        return response

def snippet_delete(request, snippet_id):
    snippet = get_object_or_404(Snippet, secret_id=snippet_id)
    try:
        snippet_list = request.session['snippet_list']
    except KeyError:
        return HttpResponseForbidden('You have no recent snippet list, '\
                                     'cookie error?')
    if not snippet.pk in snippet_list:
        return HttpResponseForbidden('That\'s not your snippet, sucka!')
    snippet.delete()
    return HttpResponseRedirect(reverse('snippet_new'))

def snippet_userlist(request, template_name='snippet/snippet_list.djhtml'):

    try:
        snippet_list = get_list_or_404(Snippet,
                                        pk__in=request.session.get(
                                           'snippet_list',
                                           None)
                                       )
    except ValueError:
        snippet_list = None

    template_context = {
        'snippets_max': getattr(settings, 'MAX_SNIPPETS_PER_USER', 10),
        'snippet_list': snippet_list,
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )


def userprefs(request, template_name='snippet/userprefs.djhtml'):

    if request.method == 'POST':
        settings_form = \
                      UserSettingsForm(request.POST,
                                       initial=\
                                       request.session.get('userprefs', None))
        if settings_form.is_valid():
            request.session['userprefs'] = settings_form.cleaned_data
            settings_saved = True
    else:
        settings_form = UserSettingsForm(initial=\
                                         request.session.get('userprefs', None))
        settings_saved = False

    template_context = {
        'settings_form': settings_form,
        'settings_saved': settings_saved,
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )

def snippet_diff(request, template_name='snippet/snippet_diff.djhtml'):

    if request.GET.get('a').isdigit() and request.GET.get('b').isdigit():
        try:
            fileA = Snippet.objects.get(pk=int(request.GET.get('a')))
            fileB = Snippet.objects.get(pk=int(request.GET.get('b')))
        except ObjectDoesNotExist:
            return HttpResponseBadRequest(u'Selected file(s) does not exist.')
    else:
        return HttpResponseBadRequest(u'You must select two snippets.')

    if fileA.content != fileB.content:
        d = difflib.unified_diff(
            fileA.content.splitlines(),
            fileB.content.splitlines(),
            'Original',
            'Current',
            lineterm=''
        )
        difftext = '\n'.join(d)
        difftext = pygmentize(difftext, 'diff')
    else:
        difftext = _(u'No changes were made between this two files.')

    template_context = {
        'difftext': difftext,
        'fileA': fileA,
        'fileB': fileB,
    }

    return render_to_response(
        template_name,
        template_context,
        RequestContext(request)
    )

def guess_lexer(request):
    code_string = request.GET.get('codestring', False)
    response = simplejson.dumps({'lexer': guess_code_lexer(code_string)})
    return HttpResponse(response)

templates/snippet/base.html
{% extends "base.djhtml" %}

templates/snippet/explore.html
{% extends "snippet/base.djhtml" %}

{% load i18n %}

{% block title %}
Explore
{% endblock %}

{% block content %}
<h2>{% trans "Recent snippets" %}</h2>

{% if recent_snippets %}
<table class="default">
    <thead>
        <tr>
            <th>{% trans "Snippet title" %}</th>
            <th>{% trans "Language" %}</th>
            <th>{% trans "Created on" %}</th>
            <th>{% trans "Views" %}</th>
            <th>{% trans "User" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for snippet in recent_snippets %}
        <tr>
            <td><a href="{{ snippet.get_absolute_url }}">
                {{ snippet.get_title }}
            </a></td>
            <td>{{ snippet.get_lexer_display }}
            <td>{{ snippet.published }}</td>
            <td>{{ snippet.num_views }}</td>
            <td>
                <a href="{{ snippet.author.get_absolute_url }}">
                    {{ snippet.author }}
                </a>
            </td>
        </tr>
    </tbody>
    {% endfor %}
</table>
{% else %}
<p>{% trans "No snippets have been created yet!" %}</p>
{% endif %}
{% endblock %}

templates/snippet/snippet_details.html
{% extends "snippet/base.html" %}
{% load mptt_tags %}
{% load i18n %}

{% block extrahead %}
     {% if request.session.userprefs %}
     <style type="text/css" media="all">
         .code{
             {# FIXME: Thats stupid #}
             {% ifnotequal request.session.userprefs.font_family "None" %}font-family: {{ request.session.userprefs.font_family }} !important;{% endifnotequal %}
             {% ifnotequal request.session.userprefs.font_size "None" %}font-size: {{ request.session.userprefs.font_size }}px !important;{% endifnotequal %}
             {% ifnotequal request.session.userprefs.line_height "None" %}line-height: {{ request.session.userprefs.line_height }}px !important;{% endifnotequal %}
         }
     </style>
     {% endif %}
{% endblock %}

{% block title %}{% trans "Snippet" %} #{{ snippet.pk }}{% endblock %}
{% block headline %}
    <h1>
        {% trans "Snippet" %} #{{ snippet.pk }}
        {% if snippet.parent_id %}
            {% blocktrans with snippet.parent.get_absolute_url as parent_url and snippet.parent.id as parent_id %}(Copy of <a href="{{ parent_url }}">snippet #{{ parent_id }}</a>){% endblocktrans %}
        {% endif %}
        <span class="date">{{ snippet.published|date:_("DATETIME_FORMAT") }} ({% trans "UTC" %})</span>
    </h1>
{% endblock %}
{% load snippet_tags %}

{% block content %}
<div id="diff" style="display:none;">diff</div>

<div class="whitebox">
    <div class="snippet-options">
        <abbr title="{% trans "Time to life" %}">TTL:</abbr> {{ snippet.expires|timeuntil  }}
        &mdash;
        {% if snippet.pk|in_list:request.session.snippet_list %}
        <a onclick="return confirm('{% trans "Really delete this snippet?" %}')" href="{% url snippet_delete snippet.secret_id %}">Delete now!</a>
        &mdash;
        {% endif %}
        <a id="toggleWordwrap" href="#">{% trans "Wordwrap" %}</a>
    </div>
    <h2>
        {% if snippet.title %}{{ snippet.title }}{% else %} {% trans "Snippet" %} #{{ snippet.id}}{% endif %}
        <span>{% if snippet.author %}{% blocktrans with snippet.author as author %}by {{ author }}{% endblocktrans %}{% endif %}</span>
    </h2>

    <div class="container">
        <div class="snippet">
        <table>
            <tr>
                <th><pre class="code">{% for l in lines %}<a href="#l{{ forloop.counter }}" id="l{{ forloop.counter }}">{{ forloop.counter }}</a>{% endfor %}</pre></th>
                <td><pre class="code">{% for line in snippet.content_splitted %}<div class="line" id="l{{ forloop.counter }}">{% if line %}{{ line|safe }}{% else %}&nbsp;{% endif %}</div>{% endfor %}</pre></td>
            </tr>
        </table>
        </div>
    </div>

    <h2>{% trans "Write an answer" %} &rarr;</h2>
    <div class="container" style="display: none;">
        {% include "snippet/snippet_form.html" %}
    </div>
</div>
{% endblock %}



{% block sidebar %}
    <h2>{% trans "History" %}</h2>

    <form method="get" id="diffform" action="{% url snippet_diff %}">
    <div class="tree">
        {% for tree_item,structure in tree|tree_info %}
        {% if structure.new_level %}<ul><li>{% else %}</li><li>{% endif %}
        <div>
        <span class="diff">
            <input type="radio" name="a" value="{{ tree_item.id }}" {% ifequal tree_item.id snippet.parent_id %}checked="checked"{% endifequal %}/>
            <input type="radio" name="b" value="{{ tree_item.id }}" {% ifequal snippet tree_item %}checked="checked"{% endifequal %}/>
        </span>
        {% ifequal snippet tree_item %}
            <strong>{% trans "Snippet" %} #{{ tree_item.id }}</strong>
       {% else %}
       <a href="{{ tree_item.get_absolute_url }}">{% trans "Snippet" %} #{{ tree_item.id }}</a>
        {% endifequal %}
        </div>
        {% for level in structure.closed_levels %}</li></ul>{% endfor %}
        {% endfor %}
        <div class="submit">
            <input type="submit" value="{% trans "Compare" %}"/>
        </div>
    </div>
    </form>

    <h2>{% trans "Options" %}</h2>
    <p><a href="{% url snippet_details_raw snippet.secret_id %}">{% trans "View raw" %}</a></p>
{% endblock %}

{% block script_footer %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.2/jquery-ui.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){

    curLine = document.location.hash;
    if(curLine.substring(0,2) == '#l'){
        $('div.snippet div.line'+curLine).addClass('marked');
    }

    $("div.accordion").accordion({
       autoHeight: false,
       header: 'h2',
       animation: 'bounceslide',
       duration: 2000,
    });

    /**
    * Diff Ajax Call
    */
    $("form#diffform").submit(function() {
        $.get("{% url snippet_diff %}", {
            a: $("input[name=a]:checked").val(),
            b: $("input[name=b]:checked").val()
        }, function(data){
            $('#diff').html(data).slideDown('fast');
        });
        return false;
    });

    /**
    * Wordwrap
    */
    $('#toggleWordwrap').toggle(
        function(){
            $('div.snippet pre.code').css('white-space', 'pre-wrap');
            return false;
        },
        function(){
            $('div.snippet pre.code').css('white-space', 'pre');
            return false;
        }
    );

    /**
    * Line Highlighting
    */
    $('div.snippet th a').each(function(i){
        $(this).click(function(){
            var j = $(this).text();
            $('div.snippet div.line.marked').removeClass('marked');
            $('div.snippet div.line#l'+j).toggleClass('marked');
        });
    });

    {% if request.session.userprefs.display_all_lexer %}
    /**
    * Lexer Guessing
    */
    $('#guess_lexer_btn').click(function(){
        $.getJSON('{% url snippet_guess_lexer %}',
            {'codestring': $('#id_content').val()},
            function(data){
                if(data.lexer == "unknown"){
                    $('#guess_lexer_btn').css('color', 'red');
                }else{
                    $('#id_lexer').val(data.lexer);
                    $('#guess_lexer_btn').css('color', 'inherit');
                }
            });
    });
    {% endif %}
});
</script>
{% endblock %}

templates/snippet/snippet_details_raw.html
{{ snippet.content|safe }}

templates/snippet/snippet_diff.html
{% load i18n %}

<h2>
    <span style="float:right;">(<a href="#" onclick="$('#diff').slideUp('fast'); return false;">{% trans "Close" %}</a>)</span>
    {% blocktrans with fileA.get_absolute_url as filea_url and fileB.get_absolute_url as fileb_url and fileA.id as filea_id and fileB.id as fileb_id %}
    Diff between
    <a href="{{ filea_url }}">Snippet #{{ filea_id }}</a>
    and
    <a href="{{ fileb_url }}">Snippet #{{ fileb_id }}</a>
    {% endblocktrans %}
</h2>

<pre class="code">{{ difftext|safe }}</pre>

templates/snippet/snippet_form.html
{% load i18n %}
<form method="post" action="." class="snippetform">
{% csrf_token %}
<ol>
    {% for field in snippet_form %}
    <li>
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
        {% if request.session.userprefs.display_all_lexer %}
        {% ifequal field.name "lexer" %}
            <input type="button" value="{% trans "Guess lexer" %}" id="guess_lexer_btn"/>
        {% endifequal %}
        {% endif %}
    </li>
    {% endfor %}
    <li class="submit"><input type="submit" value="{% trans "Paste it" %}"/></li>
</ol>
</form>

templates/snippet/snippet_list.html
{% extends "snippet/base.html" %}
{% load i18n %}

{% block title %}{% trans "Snippet" %} #{{ snippet.pk }}{% endblock %}
{% block headline %}
<h1>{% blocktrans %}Your latest {{ snippets_max }} snippets{% endblocktrans %}</h1>
{% endblock %}

{% block content %}
    {% if snippet_list %}
    {% for snippet in snippet_list %}
    <h2>
        <a href="{{ snippet.get_absolute_url }}">{% trans "Snippet" %} #{{ snippet.pk }}</a>
        ~ {{ snippet.published|date:_("DATETIME_FORMAT") }}
    </h2>
    <p style="color: #555; margin: 8px 0 20px 0;">{{ snippet.content|truncatewords:40 }}</p>
    {% endfor %}
    {% else %}
    <p>{% trans "No snippets available." %}</p>
    {% endif %}


    <div class="hint">
        {% trans "DATA_STORED_IN_A_COOKIE_HINT" %}
    </div>
{% endblock %}

templates/snippet/snippet_new.html
{% extends "snippet/base.html" %}
{% load i18n %}

{% block title %}{% trans "New snippet" %}{% endblock %}
{% block headline %}<h1>{% trans "Paste a new snippet" %}</h1>{% endblock %}

{% block content %}
    <h2>{% trans "New snippet" %}</h2>
    {% include "snippet/snippet_form.html" %}
{% endblock %}


{% block sidebar %}
    <h2>{% trans "DPASTE_HOMEPAGE_TITLE" %}</h2>
    <p>{% trans "DPASTE_HOMEPAGE_DESCRIPTION" %}</p>
{% endblock %}


{% block script_footer %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    {% if request.session.userprefs.display_all_lexer %}
    $('#guess_lexer_btn').click(function(){
        $.getJSON('{% url snippet_guess_lexer %}',
            {'codestring': $('#id_content').val()},
            function(data){
                if(data.lexer == "unknown"){
                    $('#guess_lexer_btn').css('color', 'red');
                }else{
                    $('#id_lexer').val(data.lexer);
                    $('#guess_lexer_btn').css('color', 'inherit');
                }
            });
    });
    {% endif %}
});
</script>
{% endblock %}

templates/snippet/userprefs.html
{% extends "snippet/base.html" %}
{% load i18n %}

{% block headline %}
    <h1>{% trans "User Settings" %}</h1>
{% endblock %}

{% block content %}
    {% if settings_saved %}
    <div class="success">
        {% trans "USER_PREFS_SAVED_SUCCESSFULLY" %}
    </div>
    {% endif %}

    <h2>{% trans "User Settings" %}</h2>

    <form class="snippetform" method="post" action=".">
    <ol>
        {{ settings_form.as_ul }}
        <li class="submit"><input type="submit" value="{% trans "Save settings" %}"/></li>
    </ol>
    </form>

    <div class="hint">
        {% trans "DATA_STORED_IN_A_COOKIE_HINT" %}
    </div>
{% endblock %}